## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [37]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [38]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [39]:
from sklearn.model_selection import train_test_split
X1 = X[:40]
y1 = y[:40]
X0 = X[41:]
y0 = y[41:]

In [40]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1,y1,test_size=10,random_state=1)
X_train0, X_test0, y_train0, y_test0 = train_test_split(X0,y0,test_size=10,random_state=2)

In [41]:
print('X_test1 is:\n',X_test1,'\n')
print('y_test1 is:\n',y_test1,'\n')
print('X_test0 is:\n',X_test0,'\n')
print('y_test0 is:\n',y_test0,'\n')


X_test1 is:
 [[ 10  11  12  13  14]
 [155 156 157 158 159]
 [ 15  16  17  18  19]
 [105 106 107 108 109]
 [135 136 137 138 139]
 [145 146 147 148 149]
 [110 111 112 113 114]
 [195 196 197 198 199]
 [ 95  96  97  98  99]
 [130 131 132 133 134]] 

y_test1 is:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

X_test0 is:
 [[265 266 267 268 269]
 [220 221 222 223 224]
 [970 971 972 973 974]
 [235 236 237 238 239]
 [850 851 852 853 854]
 [875 876 877 878 879]
 [560 561 562 563 564]
 [920 921 922 923 924]
 [350 351 352 353 354]
 [890 891 892 893 894]] 

y_test0 is:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [42]:
y_test = np.concatenate((y_test1,y_test0),axis=0)
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])